version: 2.1

orbs:
  catalog-build: giantswarm/catalog-build@dev:master

jobs:
  lint-scripts:
    docker:
      - image: quay.io/giantswarm/shellcheck-alpine:v0.6.0
    steps:
      - checkout
      - run:
          name: lint scripts
          command: shellcheck -x ci-scripts/*
  sync:
    machine: true
    steps:
    - checkout

    - catalog-build/catalog-build:
        reponame: $CIRCLE_PROJECT_REPONAME
        token: $PERSONAL_ACCESS_TOKEN

workflows:
  version: 2
  lint:
    jobs:
      - lint-scripts
  sync:
    triggers:
      - schedule:
          cron: "10,40 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - sync
