version: 2.1

orbs:
  catalog: giantswarm/catalog@0.0.1

jobs:
  sync:
    machine: true
    steps:
    - checkout

    - catalog/sync:
        reponame: $CIRCLE_PROJECT_REPONAME
        token: $PERSONAL_ACCESS_TOKEN

workflows:
  version: 2
  lint:
    jobs:
      - sync
  sync:
    triggers:
      - schedule:
          cron: "10,40 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - sync
